version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: UUMS_postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: uums_user
      POSTGRES_PASSWORD: uums_password
      POSTGRES_DB: uums_db
    volumes:
      - postgres-data:/var/lib/postgresql

volumes:
  postgres-data: